C:
cd/
cd \Users\nrout_admin\Automation\Applications\GitHub\Schedule\PAM\qa-pam-test-automation
ant report_email -Dtest.names="TrendAnalysisCardRegression,LoadProfileAnalysisCardRegression,CalendarLoadProfileCardRegression,ComparisonAnalysisCardRegression,ScatterPlotAnalysisCardRegression,AllCardsCommonRegression,ExceptionsAndNotificationsRegression,HierarchySheetDownloadAndUploadRegression,ManageMeasurementsRegression,ManageTagsRegression,SiteSchedulesRegression"